# Site settings
title: MGMT6963 Technology Fundamentals for Business Analytics
email: kuruzj@rpi.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the official course website for the Technology 
baseurl: "MGMT6963-2015" # the subpath of your site, e.g. /blog/
url: "http://rpi-analytics.github.io" # the base hostname & protocol for your site
twitter_username: jasonkuruzovich
github_username:  jkuruzovich
discussion_url: "https://piazza.com/rpi/fall2015/mgmt6963/home"
discussion: "Piazza"
assignment_url: "https://piazza.com/rpi/fall2015/mgmt6963/home"
assignment: "Blackboard"

# Build settings
markdown: kramdown
