# Site settings
title: MGMT6963 Technology Fundamentals for Business Analytics
email: kuruzj@rpi.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the official course website for the Technology 
baseurl: "http://jkuruzovich.github.io/MGMT6963-2015" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jasonkuruzovich
github_username:  jkuruzovich

# Build settings
markdown: kramdown
